version: '3'

services: 
  ypphp:
    container_name: php
    build: ./docker/php
    volumes:
      - ./server/src:/var/www
      - ~/etc/timezone:/etc/localtime:ro
  
  ypnginx:
    image: nginx
    container_name: nginx
    build: ./docker/nginx
    ports:
      - 80:80
    volumes:
      - ./server/src:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ~/etc/timezone:/etc/localtime:ro
    depends_on: 
      - ypphp

  cbdb:
    image: mysql:8.0.19
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cb
      MYSQL_USER: cb
      MYSQL_PASSWORD: cb
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ~/etc/timezone:/etc/localtime:ro
    ports:
      - 3306:3306